FROM apache/skywalking-oap-server:9.1.0

ADD ./log4j2.xml /skywalking/config/log4j2.xml

#ADD ./spp-skywalking-banyandb-plugin-0.5.5-SNAPSHOT.jar /skywalking/ext-libs/

#ADD ./spp-banyandb.yml .
#RUN sed -i '/\SW_STORAGE:h2}/r spp-banyandb.yml' /skywalking/config/application.yml

ADD ./spp-platform-*.jar /skywalking/oap-libs/
ADD ./spp-live-*.jar /skywalking/oap-libs/

RUN sed -i -e 's/SW_CORE_REST_PORT:12800/SW_CORE_REST_PORT:12801/g' /skywalking/config/application.yml
RUN sed -i -e 's/SW_CORE_GRPC_PORT:11800/SW_CORE_GRPC_PORT:11801/g' /skywalking/config/application.yml

RUN printf "\nspp-live-core:\n  selector: \${SPP_LIVE_CORE:default}\n  default:\n" \
    >> /skywalking/config/application.yml

RUN printf "\nspp-live-instrument:\n  selector: \${SPP_LIVE_INSTRUMENT:default}\n  default:\n" \
    >> /skywalking/config/application.yml

RUN printf "\nexporter:\n  selector: exporter\n  exporter:\n" \
    >> /skywalking/config/application.yml

ADD ./config/spp-platform.crt /skywalking/config/
ADD ./config/spp-platform.key /skywalking/config/
ADD ./config/spp-platform.yml /skywalking/config/

ADD ./config/ui-initialized-templates /skywalking/config/ui-initialized-templates
ADD ./config/self.yaml /skywalking/config/fetcher-prom-rules

ENV SW_CORE_GRPC_SSL_ENABLED=true
ENV SW_CORE_GRPC_SSL_KEY_PATH=/skywalking/config/spp-platform.key
ENV SW_CORE_GRPC_SSL_CERT_CHAIN_PATH=/skywalking/config/spp-platform.crt
ENV SW_CORE_GRPC_SSL_TRUSTED_CA_PATH=/skywalking/config/spp-platform.crt
ENV SW_RECEIVER_GRPC_SSL_ENABLED=true
ENV SW_RECEIVER_GRPC_SSL_KEY_PATH=/skywalking/config/spp-platform.key
ENV SW_RECEIVER_GRPC_SSL_CERT_CHAIN_PATH=/skywalking/config/spp-platform.crt
