FROM apache/skywalking-oap-server:8.7.0-es7

ADD ./spp-processor-*.jar /skywalking/oap-libs

RUN echo -e "\nspp-logging:" >> /skywalking/config/application.yml
RUN echo -e "  selector: \${SPP_LOGGING:default}" >> /skywalking/config/application.yml
RUN echo -e "  default:" >> /skywalking/config/application.yml

RUN echo -e "\nspp-live-instrument:" >> /skywalking/config/application.yml
RUN echo -e "  selector: \${SPP_LIVE_INSTRUMENT:default}" >> /skywalking/config/application.yml
RUN echo -e "  default:" >> /skywalking/config/application.yml

RUN echo -e "\nexporter:" >> /skywalking/config/application.yml
RUN echo -e "  selector: exporter" >> /skywalking/config/application.yml
RUN echo -e "  exporter:" >> /skywalking/config/application.yml

ADD ./config/spp-platform.crt /skywalking
ADD ./config/spp-platform.key /skywalking

#ENV SPP_PLATFORM_SSL_TRUST_ALL=true
ENV SPP_PLATFORM_HOST=spp-platform
ENV SPP_PLATFORM_PORT=5460
ENV SPP_PLATFORM_CERTIFICATE_FILE=/skywalking/spp-platform.crt

ENV SW_CORE_GRPC_SSL_ENABLED=true
ENV SW_CORE_GRPC_SSL_KEY_PATH=/skywalking/spp-platform.key
ENV SW_CORE_GRPC_SSL_CERT_CHAIN_PATH=/skywalking/spp-platform.crt
ENV SW_CORE_GRPC_SSL_TRUSTED_CA_PATH=/skywalking/spp-platform.crt
ENV SW_RECEIVER_GRPC_SSL_ENABLED=true
ENV SW_RECEIVER_GRPC_SSL_KEY_PATH=/skywalking/spp-platform.key
ENV SW_RECEIVER_GRPC_SSL_CERT_CHAIN_PATH=/skywalking/spp-platform.crt