FROM openjdk:11-jre
ADD ./spp-example-webapp-boot-1.0-SNAPSHOT.zip /

RUN mkdir -p /tmp/spp-probe/ca
ADD ./config/spp-platform.crt /tmp/spp-probe/ca/ca.crt

ADD ./spp-probe.yml /tmp/spp-probe
ADD ./spp-probe-*.jar /tmp/spp-probe/spp-probe.jar

ENV SPP_DELETE_PROBE_DIRECTORY_ON_BOOT=false

#ENV JAVA_OPTS="-javaagent:/tmp/spp-probe/spp-probe.jar"
ENV JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5105 -javaagent:/tmp/spp-probe/spp-probe.jar"

RUN unzip *.zip
CMD ["./spp-example-webapp-boot-1.0-SNAPSHOT/bin/spp-example-webapp"]