FROM apache/skywalking-oap-server:9.1.0

ADD ./spp-processor-dependencies-*.jar /skywalking/ext-libs/

ADD ./spp-processor-*.jar /skywalking/oap-libs/

RUN printf "\nspp-live-instrument:\n  selector: \${SPP_LIVE_INSTRUMENT:default}\n  default:\n" \
    >> /skywalking/config/application.yml

RUN printf "\nexporter:\n  selector: exporter\n  exporter:\n" \
    >> /skywalking/config/application.yml

ADD ./config/spp-platform.crt /skywalking
ADD ./config/spp-platform.key /skywalking

ADD ./config/ui-initialized-templates /skywalking/config/ui-initialized-templates

ADD config/self.yaml /skywalking/config/fetcher-prom-rules

#RUN mkdir -p /tmp/spp-probe/ca
#ADD ./config/spp-platform.crt /tmp/spp-probe/ca/ca.crt
#
#ADD ./spp-probe.yml /tmp/spp-probe
#ADD ./spp-probe-*.jar /tmp/spp-probe/spp-probe.jar
#
#ENV SPP_DELETE_PROBE_DIRECTORY_ON_BOOT=false

#ENV SPP_PLATFORM_SSL_TRUST_ALL=true
ENV SPP_PLATFORM_HOST=spp-platform
ENV SPP_PLATFORM_PORT=5460
ENV SPP_PLATFORM_CERTIFICATE_FILE=/skywalking/spp-platform.crt

ENV SW_CORE_GRPC_SSL_ENABLED=true
ENV SW_CORE_GRPC_SSL_KEY_PATH=/skywalking/spp-platform.key
ENV SW_CORE_GRPC_SSL_CERT_CHAIN_PATH=/skywalking/spp-platform.crt
ENV SW_CORE_GRPC_SSL_TRUSTED_CA_PATH=/skywalking/spp-platform.crt
ENV SW_RECEIVER_GRPC_SSL_ENABLED=true
ENV SW_RECEIVER_GRPC_SSL_KEY_PATH=/skywalking/spp-platform.key
ENV SW_RECEIVER_GRPC_SSL_CERT_CHAIN_PATH=/skywalking/spp-platform.crt
