spp:
  authentication:
    client_id: "test-id"
    client_secret: "test-secret"
  platform_host: "spp-platform"
  platform_port: 12800
  delete_probe_directory_on_boot: false
skywalking:
  logging:
    level: "INFO"
  agent:
    service_name: "example-jvm"
