name: Clear cache
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  clear-cache:
    runs-on: ubuntu-22.04

    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@main
