name: test gh publish

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Export Properties
        id: properties
        shell: bash
        run: |
          echo "SPP_PLATFORM_VERSION=$(echo $GITHUB_REF | cut -d / -f 3 | cut -d v -f2-)" >> $GITHUB_ENV

      - name: Publish Release Package
        run: ./gradlew -p platform publish -Dbuild.profile=release -PplatformVersion=0.0.1-SNAPSHOT
        env:
          GH_PUBLISH_USERNAME: $GITHUB_ACTOR
          GH_PUBLISH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
